services:
  phpstan:
    image: compucorp/civicrm-buildkit:1.3.1-php8.0
    platform: linux/amd64
    volumes:
      - .:/extension
      - civicrm-core:/civicrm-core
    working_dir: /extension
    command: tail -f /dev/null

volumes:
  civicrm-core:
